### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yhkaplan** [eure/swift-style-guide#15]
This is a wonderful resource, and I would like to make a version for my company, but would it be okay to fork this project?

**Comment by yhkaplan** [comment]
@JohnEstropia Sorry for the mention, but would you happen to know about permission for my company to fork this style-guide?

**Comment by JohnEstropia** [comment]
@yhkaplan Hi, sorry for the silence. Since this is open sourced, feel free to do anything with it :)

**Comment by yhkaplan** [comment]
@JohnEstropia Thanks for the confirmation! We won't sell it or anything, and I can also upstream any changes~
